version: '3'

services:

  db:
    container_name: database
    image: mysql:5.5
    hostname: database
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: ullubiy
      MYSQL_PASSWORD: 19861986
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: Root1986

  java-app:
    container_name: app
    hostname: app
    build:
      context: ./build
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ullubiy
      DB_PASSWORD: 19861986
      DB_IP: database
      DB_NAME: app

volumes:
  mysql_data: